### ISSUE TITLE
[Feature Request]  Make GUI easier to understand and create GUI for configuration.

### ISSUE THREAD

**Issue by yogert909** [ChangSpivey/MorphMan#1]
Morphman is fairly complicated to use if you aren't used to it.  Ideally it would be clear how to set up and use morphman without reading any instructions.  Hiding away some lesser used functions in the existing GUI would also be desirable.

**Comment by ChangSpivey** [comment]
MorphMan now has a GUI for card filtering + field names + tag names.

If there is a missing feature or a bug remaining - please create another issue.
