### ISSUE TITLE
ignoring stuff inside square brackets

### ISSUE THREAD

**Issue by stanaquil** [ChangSpivey/MorphMan#10]
This may have been discussed before on the forums, but between the technical level of the discussion and the fact that the addon has gone through so many changes, searching that thread makes my head ache. Point me to the relevant discussion if necessary.

Is it possible to tell MorphMan to ignore everything between [square brackets] when analyzing a sentence? I have a lot of sentences with anki-style furigana and no "clean" version of the sentence to point to.

Take this sentence:
高校[こうこう] 卒業[そつぎょう] 後[ご]、 系列[けいれつ]の 大学[だいがく]に 進[すす]みました。

Right now, from looking at the "unknown morphemes" field, I can see that MM thinks that pretty much every syllable inside the square brackets is an unknown morpheme (plus, it doesn't know that 進む is the verb, it thinks it's some random kanji). As a result, it thinks the sentence is far more complicated than it actually is. If the program could just be blind to the parentheses and everything inside them, it would be much better.

If there is some text I can add to config.py to fix this, let me know!

**Comment by ChangSpivey** [comment]
There is no easy way in MorphMan to do that. In my opinion the user is responsible to create "clean data" -  MorphMan is only there to sort that data. But I will give you the code that is necessary (not tested):

Add `e = re.sub('\[[^\]]+\]', '', e)` in front of [this](https://github.com/ChangSpivey/MorphMan/blob/78067b4add032318c0b962182ca4375bca7c354d/morph/morphemizer.py#L67). Of course I won't promise stability for the patch.

**Comment by stanaquil** [comment]
Thanks! I'll try that. I do normally try to create clean data, but sometimes things come to me that way (that sentence was from the Core10K deck).

**Comment by ChangSpivey** [comment]
I just noticed there is a regex search and replace feature in the Anki
browser. With that (and some regex knowledge) you could correct your
entries. Of course the original data would be lost without previous
backup...

**Comment by stanaquil** [comment]
Oh! I'll look into that. Maybe I could learn some regex. I'd like to be able to do that kind of editing on data when I need it. I can always make a backup copy of the deck before messing with anything.

**Comment by stanaquil** [comment]
I was able to use \[[^\]]+\] to do the search and replace inside Anki - thanks so much! I'll have to test the code in the addon as well, at some point.

That regex expression looks like a shrug emoji. ^_^;;

**Comment by ChangSpivey** [comment]
^_^;;

**Comment by FrenchYann** [comment]
Hmm I was actually looking into your plugin, and I heavily use square bracket notation to learn the writings/readings of words using the `kana:`; `kanji:`, `furigana:` template tags.

So then I was wondering. Wouldn't it be as easy as doing this?
```python
from anki.template.furigana import kanji
#...
    def getMorphemesFromExpr(self, e): # Str -> IO [Morpheme]
        return kanji(getMorphemesMecab(e))
````
I mean, if people don't use bracket notation there will pretty much be no changes, and for the ones using it, they probably expect to have the kanji version (ie: stripped bracket version) parsed. 
You could even have an option in config.py to make this, well, optional.
