### ISSUE TITLE
[Feature Request]  MacOS support

### ISSUE THREAD

**Issue by yogert909** [ChangSpivey/MorphMan#2]
for those of us thinking different;)

**Comment by ChangSpivey** [comment]
I don't remember seeing any platform dependent code in MorphMan. Even the morphemizer inside the JapaneseSupport plugin has a macOS version.

As far as I am concerned, everything should work already. Because nobody uses macOS in my surroundings, I'm relying on you for this one.

**Comment by yogert909** [comment]
Hmm, I guess I was confusing morphman with another add-on.  Because I hadn't gotten morphman working I was assuming part of the problem was my OS.  I'm getting errors in macos but it's probably because I haven't configured it properly.
btw, I'll if I have time I'll try installing the dependencies for your subtitle tool and send you the install instructions if successful.  Feel free to bug me about it if you don't hear from me in a week. 

    On Friday, October 7, 2016 11:11 PM, ChangSpivey <notifications@github.com> wrote:
 

 I don't remember seeing any platform dependent code in MorphMan. Even the morphemizer inside the JapaneseSupport plugin has a macOS version.As far as I am concerned, everything should work already. Because nobody uses macOS in my surroundings, I'm relying on you for this one.—

**Comment by ChangSpivey** [comment]
I'll close this issue for now.
