### ISSUE TITLE
NameError: global name 'none' is not defined

### ISSUE THREAD

**Issue by Solarlark** [ChangSpivey/MorphMan#3]
If I open the Anki browser window and a note type that is not defined in the settings shows up, I get the error below. For example, if I use only the following settings:

Note type: Japanese  (Core10000) | Tags: | Field: Expression | Morphemizer: Japanese | Modify: ☑

When "Nayrs Japanese Core5000" note type cards show up in the browser window, I get this error. (Same for other note types)

However, if I also add "Nayrs Japanese Core5000" to the recognized note types, I no longer get the error when these note types are viewed. The error _does_ still occur though when I view other note types.

> Traceback
> 
>  (most recent call last):
>   File "aqt\browser.py", line 90, in data
>   File "aqt\browser.py", line 214, in columnData
>   File "aqt\browser.py", line 274, in answer
>   File "aqt\browser.py", line 266, in question
>   File "anki\cards.py", line 120, in q
>   File "anki\cards.py", line 137, in _getQA
>   File "anki\collection.py", line 527, in _renderQA
>   File "anki\template\__init__.py", line 7, in render
>   File "anki\template\template.py", line 61, in render
>   File "anki\template\template.py", line 133, in render_tags
>   File "anki\template\template.py", line 196, in render_unescaped
>   File "anki\hooks.py", line 32, in runFilter
>   File "D:\Documents\Anki\addons\morph\newMorphHelper.py", line 203, in highlight
>     morphemizer = getMorphemizerForTagsAndType(fieldDict['Type'], fieldDict['Tags'].split())
>   File "D:\Documents\Anki\addons\morph\morphemes.py", line 123, in getMorphemizerForTagsAndType
>     if filter is None: return none
> NameError: global name 'none' is not defined
> Traceback (most recent call last):
>   File "aqt\browser.py", line 90, in data
>   File "aqt\browser.py", line 214, in columnData
>   File "aqt\browser.py", line 274, in answer
>   File "aqt\browser.py", line 266, in question
>   File "anki\cards.py", line 120, in q
>   File "anki\cards.py", line 137, in _getQA
>   File "anki\collection.py", line 527, in _renderQA
>   File "anki\template\__init__.py", line 7, in render
>   File "anki\template\template.py", line 61, in render
>   File "anki\template\template.py", line 133, in render_tags
>   File "anki\template\template.py", line 196, in render_unescaped
>   File "anki\hooks.py", line 32, in runFilter
>   File "D:\Documents\Anki\addons\morph\newMorphHelper.py", line 203, in highlight
>     morphemizer = getMorphemizerForTagsAndType(fieldDict['Type'], fieldDict['Tags'].split())
>   File "D:\Documents\Anki\addons\morph\morphemes.py", line 123, in getMorphemizerForTagsAndType
>     if filter is None: return none
> NameError: global name 'none' is not defined
> Traceback (most recent call last):
>   File "aqt\browser.py", line 90, in data
>   File "aqt\browser.py", line 214, in columnData
>   File "aqt\browser.py", line 274, in answer
>   File "aqt\browser.py", line 266, in question
>   File "anki\cards.py", line 120, in q
>   File "anki\cards.py", line 137, in _getQA
>   File "anki\collection.py", line 527, in _renderQA
>   File "anki\template\__init__.py", line 7, in render
>   File "anki\template\template.py", line 61, in render
>   File "anki\template\template.py", line 133, in render_tags
>   File "anki\template\template.py", line 196, in render_unescaped
>   File "anki\hooks.py", line 32, in runFilter
>   File "D:\Documents\Anki\addons\morph\newMorphHelper.py", line 203, in highlight
>     morphemizer = getMorphemizerForTagsAndType(fieldDict['Type'], fieldDict['Tags'].split())
>   File "D:\Documents\Anki\addons\morph\morphemes.py", line 123, in getMorphemizerForTagsAndType
>     if filter is None: return none
> NameError: global name 'none' is not defined
> Traceback (most recent call last):
>   File "aqt\browser.py", line 90, in data
>   File "aqt\browser.py", line 214, in columnData
>   File "aqt\browser.py", line 274, in answer
>   File "aqt\browser.py", line 266, in question
>   File "anki\cards.py", line 120, in q
>   File "anki\cards.py", line 137, in _getQA
>   File "anki\collection.py", line 527, in _renderQA
>   File "anki\template\__init__.py", line 7, in render
>   File "anki\template\template.py", line 61, in render
>   File "anki\template\template.py", line 133, in render_tags
>   File "anki\template\template.py", line 196, in render_unescaped
>   File "anki\hooks.py", line 32, in runFilter
>   File "D:\Documents\Anki\addons\morph\newMorphHelper.py", line 203, in highlight
>     morphemizer = getMorphemizerForTagsAndType(fieldDict['Type'], fieldDict['Tags'].split())
>   File "D:\Documents\Anki\addons\morph\morphemes.py", line 123, in getMorphemizerForTagsAndType
>     if filter is None: return none
> NameError: global name 'none' is not defined
> Traceback (most recent call last):
>   File "aqt\browser.py", line 90, in data
>   File "aqt\browser.py", line 214, in columnData
>   File "aqt\browser.py", line 274, in answer
>   File "aqt\browser.py", line 266, in question
>   File "anki\cards.py", line 120, in q
>   File "anki\cards.py", line 137, in _getQA
>   File "anki\collection.py", line 527, in _renderQA
>   File "anki\template\__init__.py", line 7, in render
>   File "anki\template\template.py", line 61, in render
>   File "anki\template\template.py", line 133, in render_tags
>   File "anki\template\template.py", line 196, in render_unescaped
>   File "anki\hooks.py", line 32, in runFilter
>   File "D:\Documents\Anki\addons\morph\newMorphHelper.py", line 203, in highlight
>     morphemizer = getMorphemizerForTagsAndType(fieldDict['Type'], fieldDict['Tags'].split())
>   File "D:\Documents\Anki\addons\morph\morphemes.py", line 123, in getMorphemizerForTagsAndType
>     if filter is None: return none
> NameError: global name 'none' is not defined
> Traceback (most recent call last):
>   File "aqt\browser.py", line 90, in data
>   File "aqt\browser.py", line 214, in columnData
>   File "aqt\browser.py", line 274, in answer
>   File "aqt\browser.py", line 266, in question
>   File "anki\cards.py", line 120, in q
>   File "anki\cards.py", line 137, in _getQA
>   File "anki\collection.py", line 527, in _renderQA
>   File "anki\template\__init__.py", line 7, in render
>   File "anki\template\template.py", line 61, in render
>   File "anki\template\template.py", line 133, in render_tags
>   File "anki\template\template.py", line 196, in render_unescaped
>   File "anki\hooks.py", line 32, in runFilter
>   File "D:\Documents\Anki\addons\morph\newMorphHelper.py", line 203, in highlight
>     morphemizer = getMorphemizerForTagsAndType(fieldDict['Type'], fieldDict['Tags'].split())
>   File "D:\Documents\Anki\addons\morph\morphemes.py", line 123, in getMorphemizerForTagsAndType
>     if filter is None: return none
> NameError: global name 'none' is not defined
> Traceback (most recent call last):
>   File "aqt\browser.py", line 90, in data
>   File "aqt\browser.py", line 214, in columnData
>   File "aqt\browser.py", line 274, in answer
>   File "aqt\browser.py", line 266, in question
>   File "anki\cards.py", line 120, in q
>   File "anki\cards.py", line 137, in _getQA
>   File "anki\collection.py", line 527, in _renderQA
>   File "anki\template\__init__.py", line 7, in render
>   File "anki\template\template.py", line 61, in render
>   File "anki\template\template.py", line 133, in render_tags
>   File "anki\template\template.py", line 196, in render_unescaped
>   File "anki\hooks.py", line 32, in runFilter
>   File "D:\Documents\Anki\addons\morph\newMorphHelper.py", line 203, in highlight
>     morphemizer = getMorphemizerForTagsAndType(fieldDict['Type'], fieldDict['Tags'].split())
>   File "D:\Documents\Anki\addons\morph\morphemes.py", line 123, in getMorphemizerForTagsAndType
>     if filter is None: return none
> NameError: global name 'none' is not defined
> Traceback (most recent call last):
>   File "aqt\browser.py", line 90, in data
>   File "aqt\browser.py", line 214, in columnData
>   File "aqt\browser.py", line 274, in answer
>   File "aqt\browser.py", line 266, in question
>   File "anki\cards.py", line 120, in q
>   File "anki\cards.py", line 137, in _getQA
>   File "anki\collection.py", line 527, in _renderQA
>   File "anki\template\__init__.py", line 7, in render
>   File "anki\template\template.py", line 61, in render
>   File "anki\template\template.py", line 133, in render_tags
>   File "anki\template\template.py", line 196, in render_unescaped
>   File "anki\hooks.py", line 32, in runFilter
>   File "D:\Documents\Anki\addons\morph\newMorphHelper.py", line 203, in highlight
>     morphemizer = getMorphemizerForTagsAndType(fieldDict['Type'], fieldDict['Tags'].split())
>   File "D:\Documents\Anki\addons\morph\morphemes.py", line 123, in getMorphemizerForTagsAndType
>     if filter is None: return none
> NameError: global name 'none' is not defined
> Traceback (most recent call last):
>   File "aqt\browser.py", line 90, in data
>   File "aqt\browser.py", line 214, in columnData
>   File "aqt\browser.py", line 274, in answer
>   File "aqt\browser.py", line 266, in question
>   File "anki\cards.py", line 120, in q
>   File "anki\cards.py", line 137, in _getQA
>   File "anki\collection.py", line 527, in _renderQA
>   File "anki\template\__init__.py", line 7, in render
>   File "anki\template\template.py", line 61, in render
>   File "anki\template\template.py", line 133, in render_tags
>   File "anki\template\template.py", line 196, in render_unescaped
>   File "anki\hooks.py", line 32, in runFilter
>   File "D:\Documents\Anki\addons\morph\newMorphHelper.py", line 203, in highlight
>     morphemizer = getMorphemizerForTagsAndType(fieldDict['Type'], fieldDict['Tags'].split())
>   File "D:\Documents\Anki\addons\morph\morphemes.py", line 123, in getMorphemizerForTagsAndType
>     if filter is None: return none
> NameError: global name 'none' is not defined
> Traceback (most recent call last):
>   File "aqt\browser.py", line 90, in data
>   File "aqt\browser.py", line 214, in columnData
>   File "aqt\browser.py", line 274, in answer
>   File "aqt\browser.py", line 266, in question
>   File "anki\cards.py", line 120, in q
>   File "anki\cards.py", line 137, in _getQA
>   File "anki\collection.py", line 527, in _renderQA
>   File "anki\template\__init__.py", line 7, in render
>   File "anki\template\template.py", line 61, in render
>   File "anki\template\template.py", line 133, in render_tags
>   File "anki\template\template.py", line 196, in render_unescaped
>   File "anki\hooks.py", line 32, in runFilter
>   File "D:\Documents\Anki\addons\morph\newMorphHelper.py", line 203, in highlight
>     morphemizer = getMorphemizerForTagsAndType(fieldDict['Type'], fieldDict['Tags'].split())
>   File "D:\Documents\Anki\addons\morph\morphemes.py", line 123, in getMorphemizerForTagsAndType
>     if filter is None: return none
> NameError: global name 'none' is not defined
> Traceback (most recent call last):
>   File "aqt\browser.py", line 90, in data
>   File "aqt\browser.py", line 214, in columnData
>   File "aqt\browser.py", line 274, in answer
>   File "aqt\browser.py", line 266, in question
>   File "anki\cards.py", line 120, in q
>   File "anki\cards.py", line 137, in _getQA
>   File "anki\collection.py", line 527, in _renderQA
>   File "anki\template\__init__.py", line 7, in render
>   File "anki\template\template.py", line 61, in render
>   File "anki\template\template.py", line 133, in render_tags
>   File "anki\template\template.py", line 196, in render_unescaped
>   File "anki\hooks.py", line 32, in runFilter
>   File "D:\Documents\Anki\addons\morph\newMorphHelper.py", line 203, in highlight
>     morphemizer = getMorphemizerForTagsAndType(fieldDict['Type'], fieldDict['Tags'].split())
>   File "D:\Documents\Anki\addons\morph\morphemes.py", line 123, in getMorphemizerForTagsAndType
>     if filter is None: return none
> NameError: global name 'none' is not defined
> Traceback (most recent call last):
>   File "aqt\browser.py", line 90, in data
>   File "aqt\browser.py", line 214, in columnData
>   File "aqt\browser.py", line 274, in answer
>   File "aqt\browser.py", line 266, in question
>   File "anki\cards.py", line 120, in q
>   File "anki\cards.py", line 137, in _getQA
>   File "anki\collection.py", line 527, in _renderQA
>   File "anki\template\__init__.py", line 7, in render
>   File "anki\template\template.py", line 61, in render
>   File "anki\template\template.py", line 133, in render_tags
>   File "anki\template\template.py", line 196, in render_unescaped
>   File "anki\hooks.py", line 32, in runFilter
>   File "D:\Documents\Anki\addons\morph\newMorphHelper.py", line 203, in highlight
>     morphemizer = getMorphemizerForTagsAndType(fieldDict['Type'], fieldDict['Tags'].split())
>   File "D:\Documents\Anki\addons\morph\morphemes.py", line 123, in getMorphemizerForTagsAndType
>     if filter is None: return none
> NameError: global name 'none' is not defined

**Comment by ChangSpivey** [comment]
Should be fixed now. Can I close this issue?

**Comment by Solarlark** [comment]
Got rid of old files (including DBs) and moved new files to folder. Opened Anki. Opened browser window. Clicked on a deck.  Get this error now (Same behavior for all decks/note types):

> Traceback (most recent call last):
>   File "aqt\browser.py", line 90, in data
>   File "aqt\browser.py", line 214, in columnData
>   File "aqt\browser.py", line 274, in answer
>   File "aqt\browser.py", line 266, in question
>   File "anki\cards.py", line 120, in q
>   File "anki\cards.py", line 137, in _getQA
>   File "anki\collection.py", line 527, in _renderQA
>   File "anki\template\__init__.py", line 7, in render
>   File "anki\template\template.py", line 61, in render
>   File "anki\template\template.py", line 133, in render_tags
>   File "anki\template\template.py", line 196, in render_unescaped
>   File "anki\hooks.py", line 32, in runFilter
>   File "D:\Documents\Anki\addons\morph\newMorphHelper.py", line 204, in highlight
>     ms = getMorphemes(morphemizer, txt )
>   File "D:\Documents\Anki\addons\morph\morphemes.py", line 114, in getMorphemes
>     ms = morphemizer.getMorphemesFromExpr(expression)
> AttributeError: 'NoneType' object has no attribute 'getMorphemesFromExpr'
> Traceback (most recent call last):
>   File "aqt\browser.py", line 90, in data
>   File "aqt\browser.py", line 214, in columnData
>   File "aqt\browser.py", line 274, in answer
>   File "aqt\browser.py", line 266, in question
>   File "anki\cards.py", line 120, in q
>   File "anki\cards.py", line 137, in _getQA
>   File "anki\collection.py", line 527, in _renderQA
>   File "anki\template\__init__.py", line 7, in render
>   File "anki\template\template.py", line 61, in render
>   File "anki\template\template.py", line 133, in render_tags
>   File "anki\template\template.py", line 196, in render_unescaped
>   File "anki\hooks.py", line 32, in runFilter
>   File "D:\Documents\Anki\addons\morph\newMorphHelper.py", line 204, in highlight
>     ms = getMorphemes(morphemizer, txt )
>   File "D:\Documents\Anki\addons\morph\morphemes.py", line 114, in getMorphemes
>     ms = morphemizer.getMorphemesFromExpr(expression)
> AttributeError: 'NoneType' object has no attribute 'getMorphemesFromExpr'
> Traceback (most recent call last):
>   File "aqt\browser.py", line 90, in data
>   File "aqt\browser.py", line 214, in columnData
>   File "aqt\browser.py", line 274, in answer
>   File "aqt\browser.py", line 266, in question
>   File "anki\cards.py", line 120, in q
>   File "anki\cards.py", line 137, in _getQA
>   File "anki\collection.py", line 527, in _renderQA
>   File "anki\template\__init__.py", line 7, in render
>   File "anki\template\template.py", line 61, in render
>   File "anki\template\template.py", line 133, in render_tags
>   File "anki\template\template.py", line 196, in render_unescaped
>   File "anki\hooks.py", line 32, in runFilter
>   File "D:\Documents\Anki\addons\morph\newMorphHelper.py", line 204, in highlight
>     ms = getMorphemes(morphemizer, txt )
>   File "D:\Documents\Anki\addons\morph\morphemes.py", line 114, in getMorphemes
>     ms = morphemizer.getMorphemesFromExpr(expression)
> AttributeError: 'NoneType' object has no attribute 'getMorphemesFromExpr'
> Traceback (most recent call last):
>   File "aqt\browser.py", line 90, in data
>   File "aqt\browser.py", line 214, in columnData
>   File "aqt\browser.py", line 274, in answer
>   File "aqt\browser.py", line 266, in question
>   File "anki\cards.py", line 120, in q
>   File "anki\cards.py", line 137, in _getQA
>   File "anki\collection.py", line 527, in _renderQA
>   File "anki\template\__init__.py", line 7, in render
>   File "anki\template\template.py", line 61, in render
>   File "anki\template\template.py", line 133, in render_tags
>   File "anki\template\template.py", line 196, in render_unescaped
>   File "anki\hooks.py", line 32, in runFilter
>   File "D:\Documents\Anki\addons\morph\newMorphHelper.py", line 204, in highlight
>     ms = getMorphemes(morphemizer, txt )
>   File "D:\Documents\Anki\addons\morph\morphemes.py", line 114, in getMorphemes
>     ms = morphemizer.getMorphemesFromExpr(expression)
> AttributeError: 'NoneType' object has no attribute 'getMorphemesFromExpr'
> Traceback (most recent call last):
>   File "aqt\browser.py", line 90, in data
>   File "aqt\browser.py", line 214, in columnData
>   File "aqt\browser.py", line 274, in answer
>   File "aqt\browser.py", line 266, in question
>   File "anki\cards.py", line 120, in q
>   File "anki\cards.py", line 137, in _getQA
>   File "anki\collection.py", line 527, in _renderQA
>   File "anki\template\__init__.py", line 7, in render
>   File "anki\template\template.py", line 61, in render
>   File "anki\template\template.py", line 133, in render_tags
>   File "anki\template\template.py", line 196, in render_unescaped
>   File "anki\hooks.py", line 32, in runFilter
>   File "D:\Documents\Anki\addons\morph\newMorphHelper.py", line 204, in highlight
>     ms = getMorphemes(morphemizer, txt )
>   File "D:\Documents\Anki\addons\morph\morphemes.py", line 114, in getMorphemes
>     ms = morphemizer.getMorphemesFromExpr(expression)
> AttributeError: 'NoneType' object has no attribute 'getMorphemesFromExpr'
> Traceback (most recent call last):
>   File "aqt\browser.py", line 90, in data
>   File "aqt\browser.py", line 214, in columnData
>   File "aqt\browser.py", line 274, in answer
>   File "aqt\browser.py", line 266, in question
>   File "anki\cards.py", line 120, in q
>   File "anki\cards.py", line 137, in _getQA
>   File "anki\collection.py", line 527, in _renderQA
>   File "anki\template\__init__.py", line 7, in render
>   File "anki\template\template.py", line 61, in render
>   File "anki\template\template.py", line 133, in render_tags
>   File "anki\template\template.py", line 196, in render_unescaped
>   File "anki\hooks.py", line 32, in runFilter
>   File "D:\Documents\Anki\addons\morph\newMorphHelper.py", line 204, in highlight
>     ms = getMorphemes(morphemizer, txt )
>   File "D:\Documents\Anki\addons\morph\morphemes.py", line 114, in getMorphemes
>     ms = morphemizer.getMorphemesFromExpr(expression)
> AttributeError: 'NoneType' object has no attribute 'getMorphemesFromExpr'
> Traceback (most recent call last):
>   File "aqt\browser.py", line 90, in data
>   File "aqt\browser.py", line 214, in columnData
>   File "aqt\browser.py", line 274, in answer
>   File "aqt\browser.py", line 266, in question
>   File "anki\cards.py", line 120, in q
>   File "anki\cards.py", line 137, in _getQA
>   File "anki\collection.py", line 527, in _renderQA
>   File "anki\template\__init__.py", line 7, in render
>   File "anki\template\template.py", line 61, in render
>   File "anki\template\template.py", line 133, in render_tags
>   File "anki\template\template.py", line 196, in render_unescaped
>   File "anki\hooks.py", line 32, in runFilter
>   File "D:\Documents\Anki\addons\morph\newMorphHelper.py", line 204, in highlight
>     ms = getMorphemes(morphemizer, txt )
>   File "D:\Documents\Anki\addons\morph\morphemes.py", line 114, in getMorphemes
>     ms = morphemizer.getMorphemesFromExpr(expression)
> AttributeError: 'NoneType' object has no attribute 'getMorphemesFromExpr'
> Traceback (most recent call last):
>   File "aqt\browser.py", line 90, in data
>   File "aqt\browser.py", line 214, in columnData
>   File "aqt\browser.py", line 274, in answer
>   File "aqt\browser.py", line 266, in question
>   File "anki\cards.py", line 120, in q
>   File "anki\cards.py", line 137, in _getQA
>   File "anki\collection.py", line 527, in _renderQA
>   File "anki\template\__init__.py", line 7, in render
>   File "anki\template\template.py", line 61, in render
>   File "anki\template\template.py", line 133, in render_tags
>   File "anki\template\template.py", line 196, in render_unescaped
>   File "anki\hooks.py", line 32, in runFilter
>   File "D:\Documents\Anki\addons\morph\newMorphHelper.py", line 204, in highlight
>     ms = getMorphemes(morphemizer, txt )
>   File "D:\Documents\Anki\addons\morph\morphemes.py", line 114, in getMorphemes
>     ms = morphemizer.getMorphemesFromExpr(expression)
> AttributeError: 'NoneType' object has no attribute 'getMorphemesFromExpr'
> Traceback (most recent call last):
>   File "aqt\browser.py", line 90, in data
>   File "aqt\browser.py", line 214, in columnData
>   File "aqt\browser.py", line 274, in answer
>   File "aqt\browser.py", line 266, in question
>   File "anki\cards.py", line 120, in q
>   File "anki\cards.py", line 137, in _getQA
>   File "anki\collection.py", line 527, in _renderQA
>   File "anki\template\__init__.py", line 7, in render
>   File "anki\template\template.py", line 61, in render
>   File "anki\template\template.py", line 133, in render_tags
>   File "anki\template\template.py", line 196, in render_unescaped
>   File "anki\hooks.py", line 32, in runFilter
>   File "D:\Documents\Anki\addons\morph\newMorphHelper.py", line 204, in highlight
>     ms = getMorphemes(morphemizer, txt )
>   File "D:\Documents\Anki\addons\morph\morphemes.py", line 114, in getMorphemes
>     ms = morphemizer.getMorphemesFromExpr(expression)
> AttributeError: 'NoneType' object has no attribute 'getMorphemesFromExpr'
> Traceback (most recent call last):
>   File "aqt\browser.py", line 90, in data
>   File "aqt\browser.py", line 214, in columnData
>   File "aqt\browser.py", line 274, in answer
>   File "aqt\browser.py", line 266, in question
>   File "anki\cards.py", line 120, in q
>   File "anki\cards.py", line 137, in _getQA
>   File "anki\collection.py", line 527, in _renderQA
>   File "anki\template\__init__.py", line 7, in render
>   File "anki\template\template.py", line 61, in render
>   File "anki\template\template.py", line 133, in render_tags
>   File "anki\template\template.py", line 196, in render_unescaped
>   File "anki\hooks.py", line 32, in runFilter
>   File "D:\Documents\Anki\addons\morph\newMorphHelper.py", line 204, in highlight
>     ms = getMorphemes(morphemizer, txt )
>   File "D:\Documents\Anki\addons\morph\morphemes.py", line 114, in getMorphemes
>     ms = morphemizer.getMorphemesFromExpr(expression)
> AttributeError: 'NoneType' object has no attribute 'getMorphemesFromExpr'
> Traceback (most recent call last):
>   File "aqt\browser.py", line 90, in data
>   File "aqt\browser.py", line 214, in columnData
>   File "aqt\browser.py", line 274, in answer
>   File "aqt\browser.py", line 266, in question
>   File "anki\cards.py", line 120, in q
>   File "anki\cards.py", line 137, in _getQA
>   File "anki\collection.py", line 527, in _renderQA
>   File "anki\template\__init__.py", line 7, in render
>   File "anki\template\template.py", line 61, in render
>   File "anki\template\template.py", line 133, in render_tags
>   File "anki\template\template.py", line 196, in render_unescaped
>   File "anki\hooks.py", line 32, in runFilter
>   File "D:\Documents\Anki\addons\morph\newMorphHelper.py", line 204, in highlight
>     ms = getMorphemes(morphemizer, txt )
>   File "D:\Documents\Anki\addons\morph\morphemes.py", line 114, in getMorphemes
>     ms = morphemizer.getMorphemesFromExpr(expression)
> AttributeError: 'NoneType' object has no attribute 'getMorphemesFromExpr'
> Traceback (most recent call last):
>   File "aqt\browser.py", line 90, in data
>   File "aqt\browser.py", line 214, in columnData
>   File "aqt\browser.py", line 274, in answer
>   File "aqt\browser.py", line 266, in question
>   File "anki\cards.py", line 120, in q
>   File "anki\cards.py", line 137, in _getQA
>   File "anki\collection.py", line 527, in _renderQA
>   File "anki\template\__init__.py", line 7, in render
>   File "anki\template\template.py", line 61, in render
>   File "anki\template\template.py", line 133, in render_tags
>   File "anki\template\template.py", line 196, in render_unescaped
>   File "anki\hooks.py", line 32, in runFilter
>   File "D:\Documents\Anki\addons\morph\newMorphHelper.py", line 204, in highlight
>     ms = getMorphemes(morphemizer, txt )
>   File "D:\Documents\Anki\addons\morph\morphemes.py", line 114, in getMorphemes
>     ms = morphemizer.getMorphemesFromExpr(expression)
> AttributeError: 'NoneType' object has no attribute 'getMorphemesFromExpr'
> Traceback (most recent call last):
>   File "aqt\browser.py", line 90, in data
>   File "aqt\browser.py", line 214, in columnData
>   File "aqt\browser.py", line 274, in answer
>   File "aqt\browser.py", line 266, in question
>   File "anki\cards.py", line 120, in q
>   File "anki\cards.py", line 137, in _getQA
>   File "anki\collection.py", line 527, in _renderQA
>   File "anki\template\__init__.py", line 7, in render
>   File "anki\template\template.py", line 61, in render
>   File "anki\template\template.py", line 133, in render_tags
>   File "anki\template\template.py", line 196, in render_unescaped
>   File "anki\hooks.py", line 32, in runFilter
>   File "D:\Documents\Anki\addons\morph\newMorphHelper.py", line 204, in highlight
>     ms = getMorphemes(morphemizer, txt )
>   File "D:\Documents\Anki\addons\morph\morphemes.py", line 114, in getMorphemes
>     ms = morphemizer.getMorphemesFromExpr(expression)
> AttributeError: 'NoneType' object has no attribute 'getMorphemesFromExpr'
> Traceback (most recent call last):
>   File "aqt\browser.py", line 90, in data
>   File "aqt\browser.py", line 214, in columnData
>   File "aqt\browser.py", line 274, in answer
>   File "aqt\browser.py", line 266, in question
>   File "anki\cards.py", line 120, in q
>   File "anki\cards.py", line 137, in _getQA
>   File "anki\collection.py", line 527, in _renderQA
>   File "anki\template\__init__.py", line 7, in render
>   File "anki\template\template.py", line 61, in render
>   File "anki\template\template.py", line 133, in render_tags
>   File "anki\template\template.py", line 196, in render_unescaped
>   File "anki\hooks.py", line 32, in runFilter
>   File "D:\Documents\Anki\addons\morph\newMorphHelper.py", line 204, in highlight
>     ms = getMorphemes(morphemizer, txt )
>   File "D:\Documents\Anki\addons\morph\morphemes.py", line 114, in getMorphemes
>     ms = morphemizer.getMorphemesFromExpr(expression)
> AttributeError: 'NoneType' object has no attribute 'getMorphemesFromExpr'
> Traceback (most recent call last):
>   File "aqt\browser.py", line 90, in data
>   File "aqt\browser.py", line 214, in columnData
>   File "aqt\browser.py", line 274, in answer
>   File "aqt\browser.py", line 266, in question
>   File "anki\cards.py", line 120, in q
>   File "anki\cards.py", line 137, in _getQA
>   File "anki\collection.py", line 527, in _renderQA
>   File "anki\template\__init__.py", line 7, in render
>   File "anki\template\template.py", line 61, in render
>   File "anki\template\template.py", line 133, in render_tags
>   File "anki\template\template.py", line 196, in render_unescaped
>   File "anki\hooks.py", line 32, in runFilter
>   File "D:\Documents\Anki\addons\morph\newMorphHelper.py", line 204, in highlight
>     ms = getMorphemes(morphemizer, txt )
>   File "D:\Documents\Anki\addons\morph\morphemes.py", line 114, in getMorphemes
>     ms = morphemizer.getMorphemesFromExpr(expression)
> AttributeError: 'NoneType' object has no attribute 'getMorphemesFromExpr'
> Traceback (most recent call last):
>   File "aqt\browser.py", line 90, in data
>   File "aqt\browser.py", line 214, in columnData
>   File "aqt\browser.py", line 274, in answer
>   File "aqt\browser.py", line 266, in question
>   File "anki\cards.py", line 120, in q
>   File "anki\cards.py", line 137, in _getQA
>   File "anki\collection.py", line 527, in _renderQA
>   File "anki\template\__init__.py", line 7, in render
>   File "anki\template\template.py", line 61, in render
>   File "anki\template\template.py", line 133, in render_tags
>   File "anki\template\template.py", line 196, in render_unescaped
>   File "anki\hooks.py", line 32, in runFilter
>   File "D:\Documents\Anki\addons\morph\newMorphHelper.py", line 204, in highlight
>     ms = getMorphemes(morphemizer, txt )
>   File "D:\Documents\Anki\addons\morph\morphemes.py", line 114, in getMorphemes
>     ms = morphemizer.getMorphemesFromExpr(expression)
> AttributeError: 'NoneType' object has no attribute 'getMorphemesFromExpr'

**Comment by ChangSpivey** [comment]
The cause is that you use morphHighlight in a card that isn't configured
in "preferences" (which should be valid so this is a bug). I tested it
with a similar setting. Everything should be working now.
Please test this again.

**Comment by Solarlark** [comment]
Aha! Tested again and all is well as you said. Thanks for sorting it out!
