### ISSUE TITLE
Issues with Vietnamese

### ISSUE THREAD

**Issue by NinKenDo64** [ChangSpivey/MorphMan#8]
Operating System: Windows 10 Education Edition
Anki Version: 2.0.36 & 2.0.38
MM Version: 3.8

I have encountered a number of issues with Vietnamese which appear to be caused by MorphMan's inability to handle diacritics and other modified latin letters. The first heads up I received was attempting to study my Vietnamese deck at all. While the deck would indicate new cards were due, attempting to study the deck caused a massive seize up, before the deck reported that I was done studying for the day.

Resetting cards to the end of the new card queue would again, cause the deck to report new cards due, but again, any attempt to study these cards would cause seizing, followed by the deck once again reporting a lack of new cards.

Unticking the 'Modify' box in MM Preferences did not make a difference.

Removing the rule for the Vietnamese note type entirely does seem to fix the issue somewhat, with the deck now able to be studied. However despite the deck being set to 10 new cards, it now only displays 5. Which consists of the five cards I was previously able to study as a result of removing MM entirely.

A 'deck:current is:new' search reveals the entire deck however.

Finally, what makes me suspect it is an issue with diacritics and special latin characters.

When the 'Focus Morph' field on my cards is examined, the items selected are incomplete. A card containing the word 'nhở' contains in its Focus Morph field only the two first letters 'nh', excluding the final diacritic laden character. And this pattern is repeated in all cards that feature such characters.

**Comment by ChangSpivey** [comment]
Thanks to your extensive help I've found the culprit within seconds! The hard part is how to fix it...

As a workaround you can change "\w-" (which represents all latin letters and numbers) to "\p" (which represents any non-space character) [in here](https://github.com/ChangSpivey/MorphMan/blob/a03e906b9f34cfa0f3c40e2c23fcdb78e1cb4a97/morph/morphemizer.py#L151). The problem with it is that punctuation such as "." or  ":" are now recognized as words.

Cards that are k+0 and m+0 are "buried" (=not shown until next day; represented in browser through braces around "due" number), so to reactivate them, you have to click on "Unbury" in your main deck page.

**Comment by NinKenDo64** [comment]
Awesome, that's fixed the issue of it burying all my cards. Unfortunately, now it registers individual letters as Morphemes. The note with expression "Anh sống ở đâu?" registering a Focus Morph of "u".

**Comment by ChangSpivey** [comment]
That seems strange... After some googling I found this code:

`wordList = re.findall(r"\w+", e, re.UNICODE)`

This should work correctly in all cases. Please be aware that the focus morph field is not (re)set for 'k+0 and m+n>0' cards (so an old focus morph is left there; this is a bug and will be fixed in the next version). But all cards that have the 'mm_vocab' tag should have new focus morphs.

Please let me know whether it works or not, so I can include this change in the next version.

**Comment by NinKenDo64** [comment]
That appears to have fixed the issue, although I had to manually delete all my MM dbs before recalculating. Not sure if that was expected.

**Comment by ChangSpivey** [comment]
Something like that might happen with wrong morphemizers -> wrong morphemes in db.
